# Generated by Django 4.1.3 on 2022-11-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_alter_movie_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="Images"),
        ),
    ]
